-- Insertar datos en la tabla tipoTransaccion
INSERT INTO tipoTransaccion (id, detalle, descripcion) VALUES
(1, 'VENTA', 'TRANSACCIONES QUE IDENTIFICAN VENTAS ENTRE EL USUARIO Y EL CLIENTE'),
(2, 'COMPRA', 'TRANSACCIONES QUE IDENTIFICAN COMPRAS ENTRE EL USUARIO Y EL PROVEEDOR'),
(3, 'AFILIACION', 'TRANSACCIONES QUE SE REALIZAN SOLO PARA SISTEMA Y MÓDULO DE AFILIACIONES'),
(4, 'SERVICIO', 'TRANSACCIONES QUE SE REALIZAN POR UNA PRESTACIÓN DE SERVICIOS A LOS CLIENTES'),
(5, 'TRASLADO', 'TRANSACCIONES QUE SE REALIZAN ENTRE SUCURSALES DEL MISMO NEGOCIO O ÁREAS DE UNA EMPRESA Y APLICA ENTRE PRODUCTOS, ELEMENTOS O ARTÍCULOS');
